### ISSUE TITLE
The requested accessory 'RealFakeGarageDoorsAccessory' was not registered by any plugin.

### ISSUE THREAD

**Issue by StefanMeGit** [plasticrake/homebridge-real-fake-garage-doors#1]
H, after installing i got this error:

I installed it over NPM
`npm install -g homebridge-real-fake-garage-doors`

```
        "accessories": [{
                "accessory": "RealFakeGarageDoorsAccessory",
                "name": "TestGarage",
                "host": "localhost",
                "port": 3893,
                "key": "wubbalubbadubdub",
                "openCommand": 2,
                "closeAfter": 20,
                "simulateTimeOpening": 5,
                "simulateTimeOpen": 15,
                "simulateTimeClosing": 5
        }]
```

```
[2/5/2017, 9:55:24 PM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:60
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'RealFakeGarageDoorsAccessory' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:60:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

```

**Comment by sebastienvermeille** [comment]
same here

**Comment by cerniuk** [comment]
Same error. And unfortunately this also means that it disables all of homebridge instead of homebridge just shrugging it off and nullifying the fail.

**Comment by Kepete** [comment]
This means the installation was not successful. Make sure you didn't get any error messages while installing. 

@cerniuk You can get homebridge always back running when you remove the "RealFakeGarageDoorsAccessory" accessory from the config.json.

**Comment by danifri** [comment]
Is there still support here? 
Really like the thought of this plugin but have the same issue.
Installation is fine. no errors. please help me.

**Comment by sohnkarlsruhe** [comment]
There is a failure in the sample code
with this the plug-in works fine
"accessory": "RealFakeGarageDoors",
